version: "3.6"
services:
  unciv:
    image: containers.cerno.ch/handy/uniciv:4.5.17
    volumes:
      - config:/server/MultiplayerFiles
    networks:
      - proxy-sites
volumes:
  config:
networks:
  proxy-sites:
    external: true
